-- print first_table table description

SELECT CONCAT('CREATE TABLE `', TABLE_NAME, '` (', GROUP_CONCAT(COLUMN_NAME, ' ', COLUMN_TYPE, ' ', IF(IS_NULLABLE = 'NO', 'NOT NULL', ''), IF(COLUMN_DEFAULT IS NOT NULL, CONCAT('DEFAULT ', COLUMN_DEFAULT), ''), IF(EXTRA = 'auto_increment', 'AUTO_INCREMENT', ''), IF(COLUMN_KEY = 'PRI', 'PRIMARY KEY', ''), ''), ') ENGINE=InnoDB DEFAULT CHARSET=latin1;') AS 'Create Table'
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'first_table';
